//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessangingAppApi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public string userName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ReplyContent { get; set; }
        public int PostId { get; set; }
    }
}
